name: CICD_Hello_app

on:
  push:
    branches: [ master ]
  
jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd ./py_program_1 && docker build . -t shamrockoo4tune/pyapp:${{ github.sha }} -f ../dockerfiles/PyDockerfile
    - name: Push to Docker Hub repo
      run: docker push shamrockoo4tune/pyapp:${{ github.sha }}
      
  deploy_docker_container:
    runs-on: ubuntu-latest
    needs: [ build_and_push_docker_image ]
    steps:
    - name: say hello
      run: echo "hello from Deploy Docker Container job"
      
