name: CICD_Hello_app

on:
  push:
    branches: [ master ]
  
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd ./py_program_1 && docker build . -t pyapp:$(date +%d.%m.%Y-%H:%M) -f ../dockerfiles/PyDockerfile
  
  deploy_docker_container:
    runs-on: ubuntu-latest
    needs: [ build_docker_image ]
    steps:
    - name: say hello
      run: echo "hello from Deploy Docker Container job"
      
