name: CICD_Hello_app

on:
  push:
    branches: [ master ]

env:
  AWS_REGION_NAME:        "eu-central-1"
  and_exam_webserver1_id: "i-0dfeddfbfeb6b1307"
  and_exam_webserver2_id: "i-0d82503bf53a1cd64"
  docker-image:           "shamrockoo4tune/pyapp:${{ github.sha }}"
  
jobs:
  build_and_push_docker_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd ./py_program_1 && docker build . -t ${{ env.docker-image }} -f ../dockerfiles/PyDockerfile
    # uncomment when needed to avoid excess traffic while continue developing pipeline
    # - name: Login to Docker Hub
    #   run: docker login -u shamrockoo4tune -p ${{ secrets.SHAMROCKOO4TUNE_DOCKERHUB_PASSWORD }}
    # - name: Push to Docker Hub repo
    #   run: docker push ${{ env.docker-image }}
  
  user_acceptance_test:
    runs-on: ubuntu-latest
    needs: [ build_and_push_docker_image ]
    outputs:
      output1: ${{ steps.set_result.outputs.test }}
    steps:
    - name: Pull Docker image
      #fix this line when ready to switch for versioned containers pull
      run: docker pull shamrockoo4tune/pyapp:7b956242d8c397a624195ed5641a67bc68a6f53e
    - name: Start docker container
      run: docker run -d -p 8080:8080 shamrockoo4tune/pyapp:7b956242d8c397a624195ed5641a67bc68a6f53e
    - id: set_result
      continue-on-error: true
      run: |
        sleep 5 # curl fails if called immediately without time delay
        echo "::set-output name=test::$(curl http://localhost:8080 -sS 2>/dev/null)"
      
  deploy_in_aws:
    runs-on: ubuntu-latest
    needs: [ build_and_push_docker_image, user_acceptance_test ]
    if: needs.user_acceptance_test.outputs.output1 != '' # deploy only if test passed i.e. curl returns something from webserver 
    steps:
    #- name: Print acceptance test result - curl reply from webserver (Hello World)
    #  run: echo ${{ needs.user_acceptance_test.outputs.output1 }}
    - name: install AWS CLI
      run: |
        sudo apt-get install awscli -y
        aws --version
    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region:            ${{ env.AWS_REGION_NAME }}
    - name: Start webserver
      run: aws ec2 start-instances --instance-ids ${{ env.and_exam_webserver1_id }}  
    - id: get_webserver1_ip
      run: |
        # let some time for AWS EC2 to get up and running:
        sleep 20 
        echo "::set-output name=public_ip::$(aws ec2 describe-instances --filters 'Name=instance-id,Values= ${{ env.and_exam_webserver1_id }}' --query 'Reservations[*].Instances[*].[PublicIpAddress]' --output text)"
    - name: pull docker image to EC2 webserver1 and start container
      run: aws ssm send-command --document-name "AWS-RunShellScript" --parameters 'commands=["docker pull shamrockoo4tune/pyapp:7b956242d8c397a624195ed5641a67bc68a6f53e && docker run -d -p 80:8080 shamrockoo4tune/pyapp:7b956242d8c397a624195ed5641a67bc68a6f53e"]' --targets "Key=instanceids,Values=i-0dfeddfbfeb6b1307" --comment "pull image and run docker container"
    - name: Print webserver1 public IP
      run: echo "webserver1 ready to serve @ ${{ steps.get_webserver1_ip.outputs.public_ip }}:80"
      
      
