name: CICD_Hello_app

on:
  push:
    branches: [ master ]
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd ./py_program_1 && docker build . -t pyapp:$(date +%d.%m.%Y@%H:%M) -f ../dockerfiles/PyDockerfile
